openeuropa/oe_contact_forms

README.md
composer.json

Add granular permission through drupal.org issue #2708809 patch.
- Added: patch revisit_permissions-2708809-56.patch

OPENEUROPA-3039: Add granular permissions

---

composer.json

Update rdf skos version.
- Changed: rdf_skos version to 0.8.0
- Removed: 0.7.0...master.diff patch

OPENEUROPA-3282: Update rdf skos version.

---

oe_contact_forms.module
src/Access/ContactFormsAccessCheck.php
src/Routing/ContactFormRouteSubscriber.php
tests/src/Kernel/AccessTest.php

Fix contact form canonical route permissions.
- Added: delegate to hook_ENTITY_TYPE_create_access for canonical route
- Changed: skos field formatter setting for oe_country_residence

OPENEUROPA-3282: Fix contact form canonical route permissions.

---

oe_contact_forms.info.yml
oe_contact_forms.module
src/Form/ContactMessageForm.php
tests/src/FunctionalJavascript/CorporateContactFormTest.php
tests/src/FunctionalJavascript/MessageFormTest.php

Change privacy policy to accept internal links.
- Added:
- dependency to drupal:link
- tests for internal privacy policy links
- Changed:
- privacy policy to entity_autocomplete
- telephone field display option from 'tel' to 'telephone_default'

D8TEWPPE-60: Change privacy policy to accept internal links.

---

oe_contact_forms.module
src/Access/ContactFormsAccessCheck.php
src/Plugin/Block/CorporateFormBlock.php
tests/src/FunctionalJavascript/CorporateContactFormTest.php
tests/src/Kernel/AccessTest.php

Remove disable message, add check for disabled contact form in block.
- Added: Check for disabled contact forms in CorporateFormBlock.php 
- Removed: contact_storage_disabled_form_message
- Fixed: Disabled form appearing in blocks

EWPP-152: Remove disable message, add check for disabled contact form

---

composer.json
oe_contact_forms.info.yml
oe_contact_forms.module
oe_contact_forms.post_update.php
tests/src/FunctionalJavascript/MessageFormTest.php
tests/src/Kernel/ContactFormTestBase.php

Add filters and ordering for country field
- Added: Add filters and ordering for country field
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

EWPP-176: Add filters and ordering for country field

---

oe_contact_forms.module
tests/src/Kernel/BlocksTest.php

Disable caching of topic options_allowed_values.
- Changed: options_allowed_values in for oe_topic

EWPP-177: Disable caching of topic options_allowed_values.

---

composer.json

Update rdf_skos dependency to allow to include minor versions.
- Added:
- Changed: Update rdf_skos dependency to 0.11
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

EWPP-280: Update rdf_skos dependency to allow to include minor versions.

---

CHANGELOG.md

Prepare release 0.3.0.
- Added:
- Changed:  Prepare release 0.3.0.
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

 Prepare release 0.3.0.

---

composer.json

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

EWPP-529: Update scaffold library.

---

CHANGELOG.md

Prepare release 0.6.0.
- Added:
- Changed: Update changelog for relase 0.6.0
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

Prepare release 0.6.0.

---

.gitignore
composer.json
phpunit.xml.dist
runner.yml.dist
tests/src/FunctionalJavascript/MessageFormTest.php
tests/src/Kernel/AccessTest.php
tests/src/Kernel/ContactFormTestBase.php

Use dev branches for the rdf_skos update.
- Added:
- Changed: Use dev branches for the rdf_skos update.
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

EWPP-109: Use dev branches for the rdf_skos update.

---

CHANGELOG.md

Prepare release 1.0.0
- Added:
- Changed: Prepare release 1.0.0
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

Prepare release 1.0.0.

---

.drone.yml
README.md
behat.yml.dist
composer.json
docker-compose.yml
oe_contact_forms.info.yml
oe_contact_forms.install
oe_contact_forms.module
phpunit.xml.dist
runner.yml.dist
tests/src/Functional/ContactFormSanitizeCommandTest.php
tests/src/FunctionalJavascript/CorporateContactFormTest.php
tests/src/FunctionalJavascript/MessageFormTest.php
tests/src/Kernel/AccessTest.php
tests/src/Kernel/BaseFieldTest.php
tests/src/Kernel/BlocksTest.php
tests/src/Kernel/ContactFormTestBase.php

Drupal 9 compatibility fixes
- Added: core version 8 || 9, other additions
- Changed:
- Deprecated:
- Removed: require-dev dependencies from composer
- Fixed:
- Security:
```sh
```

OEL-164: Drupal 9 compatibility fixes.

---

.drone.yml
composer.json
docker-compose.yml
grumphp.yml.dist

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

EWPP-1845: Update PHP8

---

modules/oe_contact_forms_honeypot/README.md
modules/oe_contact_forms_honeypot/tests/src/Functional/HoneypotTest.php

Fix comments.
- Changed: Comments in honeypot test

OEL-0000: Fix comments in honeypot test

---

composer.json

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

EWPP-2035: Revert fixing xdebug-handler version.

---

src/Commands/sql/ContactFormSanitizeCommand.php
tests/src/Functional/ContactFormSanitizeCommandTest.php

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

EWPP-1672: Sanitize emails of contact forms.

---

CHANGELOG.md

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

Prepare release 1.4.0.

---

CHANGELOG.md

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

Prepare release 1.5.0.

---

CHANGELOG.md
composer.json

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

Prepare release 1.6.0.

---

composer.json

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

EWPP: Bump contact storage version and remove patch.

---

composer.json

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

EWPP-2751: Reapply permissions patch.

---

tests/src/FunctionalJavascript/CorporateContactFormTest.php

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

EWPP-0000: Assert machine name is correctly set during tests.

---

tests/src/Functional/ContactFormSanitizeCommandTest.php

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

EWPP-000: Fix ContactFormSanitizeCommandTest.

---

CHANGELOG.md

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

Prepare release 1.13.0

---

composer.json
oe_contact_forms.info.yml
tests/src/FunctionalJavascript/CorporateContactFormTest.php

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

EWPP-3905: Patch sparql entity storage for D10.2 support.

---

CHANGELOG.md

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

Prepare release 1.14.0.

---

.drone.yml
config/schema/oe_contact_forms.views.schema.yml
oe_contact_forms.module
src/Plugin/views/field/ContactMessageRemainingDays.php
tests/modules/oe_contact_forms_test_views/oe_contact_forms_test_views.info.yml
tests/modules/oe_contact_forms_test_views/test_views/views.view.contact_messages_test.yml
tests/src/Functional/RemainingDaysTest.php

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

EWPP-4157: Add cron function to delete old contact messages.

---

.drone.yml
README.md
docker-compose.yml

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

EWPP-5461: Update sparql image in docker-compose.yml and for drone.yml.
